config/routes.rb
Pinteresting::Application.routes.draw do
  devise_for :users
  root "pages#home"
  get "about" => "pages#about"
  get "fun" => "pages#fun"
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  def fun
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">  
    <!-- Brand and toggle get grouped for better mobile display -->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pinteresting", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Fun", fun_path %></li>
        <% if user_signed_in? %>
         <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "sign in", new_user_path %></li>
        <% end %>  
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
 	 <title>Pinteresting</title>
 	 <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
 	 <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
 	<%= csrf_meta_tags %>
 	 <meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body>
  
		<%= render 'layouts/header' %>
		<% end %>
		<div class="container">
			<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg,class: "alert alert-info") %>
			<%= yield %>
		</div>
	</body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>We are working on our One Month Rails Pinteresting app!</p>

app/views/pages/fun.html.erb
<h1>Fun</h1>
<p>Our goal is to bring a smile to your face.</p>
<h3>Humorous quotes</h3>

<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img data-src="holder.js/300x200" alt="...">
      <div class="caption">
        <h3>Winston Churchill</h3>
        <p>If you feel that you're going through hell, keep moving.</p>
        <p><a href="#" class="btn btn-primary" role="button">More Churchill</a> <a href="#" class="btn btn-default" role="button">Other humourists</a></p>
      </div>
      <img data-src="holder.js/300x200" alt="...">
      <div class="caption">
        <h3>Ambrose Bierce</h3>
        <p>Egotist: A person of low taste, more interested in himself than me.</p>
        <p><a href="#" class="btn btn-primary" role="button">More Bierce</a> <a href="#" class="btn btn-default" role="button">Other humourists</a></p>
     </div>
      <img data-src="holder.js/300x200" alt="...">
        <div class="caption">
        <h3>Mark Twain</h3>
        <p>Suppose you were an idiot, and suppose you were a member of Congress; but I repeat myself.</p>
        <p><a href="#" class="btn btn-primary" role="button">More Twain</a> <a href="#" class="btn btn-default" role="button">Other humourists</a></p>
      </div>
    </div>
  </div>
<h3>What makes you laugh?</h3>
<p>Share your favorite quote or story with us.</p>
<h5>Your Email</h5>
<form class="form-inline" role="form">
  <div class="form-group">
    <label class="sr-only" for="exampleInputEmail2">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail2" placeholder="Enter email">
  </div>
<h5>Your Favorite</h5>
  <div>
 <input type="text" class="form-control" placeholder="Quote or story"></div>
</p>By clicking submit you give us permission to share your story on this site with attribution to you.  Your contact information will NOT be shared with anyone.</p>
 <button type="submit" class="btn btn-default">Submit</button>
</form>
<h3></h3>
<P>Feel free to make multiple submissions. Thank you for giving us another reason to laugh!</p>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to my app!</h1>
	<% if user_signed_in? %>
		# do something
	<% else	%>
		<p>
       <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
       <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  	</p> 
  <% end %>	
</div>